version: '3.4'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: chatter-db
      POSTGRES_USER: chatter-server
      POSTGRES_PASSWORD: Password1
    ports:
      - "5432:5432"
      
  chatter.api:
    image: chatter.api
    build:
      context: .
      dockerfile: Chatter.Api/Dockerfile
